import { writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  ALL_TOOL_DEFINITIONS,
  filterToolDefinitions,
  TOOL_CATEGORY_BY_NAME,
  type FilterToolsOptions,
} from "@andrewkimjoseph/celina-sdk/tools";
import { assignAliases } from "../src/alias-derive.js";

export type GeneratedAliasEntry = {
  tool: string;
  alias: string;
  title: string;
  category: string;
};

/** Same filter as celina-api/src/catalog.ts — keep in sync. */
export const PUBLIC_READ_FILTER: FilterToolsOptions = {
  surface: "mcp",
  families: ["read"],
  serverKeyToolsEnabled: false,
  selfSessionToolsEnabled: false,
  estimateToolsEnabled: false,
};

function titleFromName(name: string): string {
  return name
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function categoryFor(name: string): string {
  const mapped = TOOL_CATEGORY_BY_NAME[name];
  if (mapped) return mapped;
  if (/gas|block|network|transaction|attribution/.test(name)) return "Blockchain";
  return "Other";
}

export function generateAliasEntries(): GeneratedAliasEntry[] {
  const tools = filterToolDefinitions(ALL_TOOL_DEFINITIONS, PUBLIC_READ_FILTER);
  const names = tools.map((tool) => tool.name);
  const aliases = assignAliases(names);
  return tools.map((tool) => ({
    tool: tool.name,
    alias: aliases.get(tool.name) ?? tool.name,
    title: tool.mcp?.title ?? titleFromName(tool.name),
    category: categoryFor(tool.name),
  }));
}

export function renderGeneratedAliasesFile(entries: GeneratedAliasEntry[]): string {
  return `// Generated by scripts/generate-aliases.ts — do not hand-edit.
// Re-run \`npm run sync-aliases\` after bumping @andrewkimjoseph/celina-sdk.

export type GeneratedAliasEntry = {
  tool: string;
  alias: string;
  title: string;
  category: string;
};

export const GENERATED_ALIASES: GeneratedAliasEntry[] = ${JSON.stringify(entries, null, 2)};
`;
}

const invoked = process.argv[1] ? resolve(process.argv[1]) : "";
if (fileURLToPath(import.meta.url) === invoked) {
  const root = join(dirname(fileURLToPath(import.meta.url)), "..");
  const outPath = join(root, "src/aliases.generated.ts");
  const entries = generateAliasEntries();
  writeFileSync(outPath, renderGeneratedAliasesFile(entries), "utf8");
  console.log(`Wrote ${entries.length} aliases to ${outPath}`);
}
