// Generated by scripts/generate-aliases.ts — do not hand-edit.
// Re-run `npm run sync-aliases` after bumping @andrewkimjoseph/celina-sdk.

export type GeneratedAliasEntry = {
  tool: string;
  alias: string;
  title: string;
  category: string;
};

export const GENERATED_ALIASES: GeneratedAliasEntry[] = [
  {
    "tool": "get_network_status",
    "alias": "network_status",
    "title": "Get Network Status",
    "category": "Blockchain"
  },
  {
    "tool": "get_block",
    "alias": "block",
    "title": "Get Block",
    "category": "Blockchain"
  },
  {
    "tool": "get_latest_blocks",
    "alias": "latest_blocks",
    "title": "Get Latest Blocks",
    "category": "Blockchain"
  },
  {
    "tool": "get_transaction",
    "alias": "transaction",
    "title": "Get Transaction",
    "category": "Blockchain"
  },
  {
    "tool": "verify_attribution_tag",
    "alias": "verify_attribution_tag",
    "title": "Verify Attribution Tag",
    "category": "Blockchain"
  },
  {
    "tool": "check_attribution_tag",
    "alias": "check_attribution_tag",
    "title": "Check Attribution Tag",
    "category": "Blockchain"
  },
  {
    "tool": "get_account",
    "alias": "account",
    "title": "Get Account",
    "category": "Account"
  },
  {
    "tool": "get_celo_account_registration",
    "alias": "celo_account_registration",
    "title": "Get Celo Account Registration",
    "category": "Account"
  },
  {
    "tool": "get_celo_balances",
    "alias": "celo_balances",
    "title": "Get Celo Balances",
    "category": "Token"
  },
  {
    "tool": "get_stablecoin_balances",
    "alias": "stablecoin_balances",
    "title": "Get Stablecoin Balances",
    "category": "Token"
  },
  {
    "tool": "get_token_info",
    "alias": "token_info",
    "title": "Get Token Info",
    "category": "Token"
  },
  {
    "tool": "get_token_balance",
    "alias": "token_balance",
    "title": "Get Token Balance",
    "category": "Token"
  },
  {
    "tool": "get_gas_fee_data",
    "alias": "gas_fee_data",
    "title": "Get Gas Fee Data",
    "category": "Blockchain"
  },
  {
    "tool": "get_mento_fx_quote",
    "alias": "mento_fx_quote",
    "title": "Get Mento FX Quote",
    "category": "Mento FX"
  },
  {
    "tool": "get_uniswap_quote",
    "alias": "uniswap_quote",
    "title": "Get Uniswap Quote",
    "category": "Uniswap"
  },
  {
    "tool": "get_aave_balances",
    "alias": "aave_balances",
    "title": "Get Aave Balances",
    "category": "Aave"
  },
  {
    "tool": "resolve_ens",
    "alias": "ens",
    "title": "Resolve ENS",
    "category": "Wallet"
  },
  {
    "tool": "get_gooddollar_whitelisting_info",
    "alias": "gooddollar_whitelisting_info",
    "title": "Get GoodDollar Whitelisting Info",
    "category": "GoodDollar"
  },
  {
    "tool": "get_gooddollar_identity_link",
    "alias": "gooddollar_identity_link",
    "title": "Get GoodDollar Identity Link",
    "category": "GoodDollar"
  },
  {
    "tool": "get_gooddollar_ubi_entitlement",
    "alias": "gooddollar_ubi_entitlement",
    "title": "Get GoodDollar UBI Entitlement",
    "category": "GoodDollar"
  },
  {
    "tool": "get_gooddollar_reserve_quote",
    "alias": "gooddollar_reserve_quote",
    "title": "Get GoodDollar Reserve Quote",
    "category": "GoodDollar"
  },
  {
    "tool": "get_governance_proposals",
    "alias": "governance_proposals",
    "title": "Get Governance Proposals",
    "category": "Governance"
  },
  {
    "tool": "get_proposal_details",
    "alias": "proposal_details",
    "title": "Get Proposal Details",
    "category": "Governance"
  },
  {
    "tool": "get_locked_celo_balance",
    "alias": "locked_celo_balance",
    "title": "Get Locked CELO Balance",
    "category": "Governance"
  },
  {
    "tool": "get_pending_withdrawals",
    "alias": "pending_withdrawals",
    "title": "Get Pending Withdrawals",
    "category": "Governance"
  },
  {
    "tool": "get_votable_proposals",
    "alias": "votable_proposals",
    "title": "Get Votable Proposals",
    "category": "Governance"
  },
  {
    "tool": "get_queued_proposals",
    "alias": "queued_proposals",
    "title": "Get Queued Proposals",
    "category": "Governance"
  },
  {
    "tool": "get_actionable_governance_proposals",
    "alias": "actionable_governance_proposals",
    "title": "Get Actionable Governance Proposals",
    "category": "Governance"
  },
  {
    "tool": "get_governance_votes",
    "alias": "governance_votes",
    "title": "Get Governance Votes",
    "category": "Governance"
  },
  {
    "tool": "check_humanness",
    "alias": "humanness",
    "title": "Check Humanness",
    "category": "Humanness"
  },
  {
    "tool": "get_staking_balances",
    "alias": "staking_balances",
    "title": "Get Staking Balances",
    "category": "Staking"
  },
  {
    "tool": "get_activatable_stakes",
    "alias": "activatable_stakes",
    "title": "Get Activatable Stakes",
    "category": "Staking"
  },
  {
    "tool": "get_validator_groups",
    "alias": "validator_groups",
    "title": "Get Validator Groups",
    "category": "Staking"
  },
  {
    "tool": "get_validator_group_details",
    "alias": "validator_group_details",
    "title": "Get Validator Group Details",
    "category": "Staking"
  },
  {
    "tool": "get_total_staking_info",
    "alias": "total_staking_info",
    "title": "Get Total Staking Info",
    "category": "Staking"
  },
  {
    "tool": "get_delegation_info",
    "alias": "delegation_info",
    "title": "Get Delegation Info",
    "category": "Staking"
  },
  {
    "tool": "get_stake_eligibility",
    "alias": "stake_eligibility",
    "title": "Get Stake Eligibility",
    "category": "Staking"
  },
  {
    "tool": "get_governance_delegates",
    "alias": "governance_delegates",
    "title": "Get Governance Delegates",
    "category": "Staking"
  },
  {
    "tool": "get_governance_delegate_details",
    "alias": "governance_delegate_details",
    "title": "Get Governance Delegate Details",
    "category": "Staking"
  },
  {
    "tool": "get_nft_info",
    "alias": "nft_info",
    "title": "Get NFT Info",
    "category": "NFT"
  },
  {
    "tool": "get_nft_balance",
    "alias": "nft_balance",
    "title": "Get NFT Balance",
    "category": "NFT"
  },
  {
    "tool": "call_contract_function",
    "alias": "contract_function",
    "title": "Call Contract Function",
    "category": "Contract"
  },
  {
    "tool": "verify_self_agent",
    "alias": "self_agent",
    "title": "Verify Self Agent",
    "category": "Self"
  },
  {
    "tool": "lookup_self_agent",
    "alias": "lookup_self_agent",
    "title": "Look Up Self Agent",
    "category": "Self"
  },
  {
    "tool": "verify_self_request",
    "alias": "self_request",
    "title": "Verify Self Agent Request",
    "category": "Self"
  },
  {
    "tool": "get_agentkarma_reputation",
    "alias": "agentkarma_reputation",
    "title": "Get AgentKarma Reputation",
    "category": "AgentKarma"
  },
  {
    "tool": "get_agentkarma_celo_agent",
    "alias": "agentkarma_celo_agent",
    "title": "Get AgentKarma Celo Agent",
    "category": "AgentKarma"
  },
  {
    "tool": "check_agentkarma_counterparty",
    "alias": "agentkarma_counterparty",
    "title": "Check AgentKarma Counterparty",
    "category": "AgentKarma"
  }
];
